#+TITLE: Control Group Website

This is the repository containing the website of [[https://iitdcon.github.io/index.html][Control Group]] of the [[https://ee.iitd.ac.in][Department
of Electrical Engineering]], [[https://home.iitd.ac.in][Indian Institute of Technology, Delhi]]. The website
is dynamically updated on the client-side using the [[https://vuejs.org][Vue.js]] framework loaded via
a CDN. To update the website, one just has to update the corresponding JSON file
in 'assets/data/' folder. *DO NOT* update the html files directly.

* Example JSON data schema
** faculty.json (For faculty.html page)
#+begin_src json
  {
    "name": "Indra Narayan Kar",
	"avatar": "/assets/img/faculty/ink.jpg",
    "position": "Professor and Head of the Department",
    "education": "Ph.D. and M.Tech. IIT Kanpur, B.E. Bengal Engineering College",
    "research": [
      "Robotics",
      "Time-delay systems",
      "Mechatronics",
      "Robust-Optimal Control Theory and its Applications",
      "Control and security of cyber-physical systems",
      "Distributed optimization and applications",
      "Incremental stability and Contraction analysis of nonlinear systems"
    ],
    "room": "Room No. 322, Block 2",
    "email": "ink[AT]ee.iitd.ac.in",
    "homepage": "http://web.iitd.ac.in/~ink/"
  },

#+end_src
** fullphd.json (For phd.html page)
#+begin_src json
{
	"name" : "Mr. Eswara Venkata Kumar",
	"area" : "Multi-Agent Systems",
	"supervisor" : "Prof. Deepak Patil",
	"joining" : "January, 2017",
	"room": "Block 2, 214",
	"email" : "eez168497 [at] ee.iitd.ac.in",
	"avatar" : "assets/img/scholars/phd_eswar.jpg"
    "website": "https://www.google.com"
},


#+end_src
** msr.json (For msr.html page)
#+begin_src json
{
"name" :" Mr. Sunil Kumar",
"area" :" Trajectory Tracking of Robotic Manipulators",
"supervisor" :"Prof. S. Janardhanan and Prof. Shubhendu Bhasin",
"joining" :"July, 2021 ",
"email" :" eey217524@ee.iitd.ac.in",
"avatar" : "assets/img/staff/staff_sunil.jpg"
},
#+end_src
** msrAlumni.json (For alumni.html page)
#+begin_src json
  {
    "name": "Mr. Sourodip Chowdhury",
    "thesis": "Ground Contact Sensors Calibration for an IoT Enabled Soil Moisture Measurement Platform",
    "supervisor": "Prof. Shaunak Sen and Prof. S. Janardhanan",
    "year": "2022",
    "current": "Software Engineer, Rakuten Mobile Inc., Japan",
    "avatar": "assets/img/scholars/Sourdeep.jpeg"
  },

#+end_src
** partphd.json (For phd.html page)
#+begin_src json
{
    	"name": "Mr. Ranjan Dasgupta",
    	"area": "Multi-Body Dynamics and Nonlinear Control of a N-DOF Floating Base Manipulator",
    	"supervisor": "Prof. Shubhendu Bhasin",
    	"joining": "January 2016",
    	"email": "eez158420[at]ee.iitd.ac.in",
    	"avatar": "assets/img/scholars/ran_das.jpg"
 },

#+end_src
** pastFaculty.json (For faculty.html page)
#+begin_src json
 {
    "name": "Nesar Ahmad",
    "current": "Professor at MIT and Cambridge"
  },
#+end_src
** pgcourses.json (For pgcourses.html page)
#+begin_src json
    {
        "id": "ELL700",
        "name": "Linear Systems Theory ",
        "credit": "(3-0-0)",
        "description": "Review of matrix algebra, state variable modelling of continuous and discrete time systems, linearization of state equations, solution of state equations of linear time-invariant and timevarying systems, Controllability and observability of dynamical systems, Minimal realization of linear systems and canonical forms, Lyapunov's stability theory for linear dynamical systems, State Feedback controllers, Observer and Controller design.",
        "core": "yes"
    },
#+end_src
** phdAlumni.json (For alumni.html page)
#+begin_src json
{
	"name":"Dr. Syed Muhammad Amrr",
    "thesis":"Advanced Robust Strategies for Attitude Control of Spacecraft",
    "supervisor":"Prof. M. Nabi",
    "year":"2021",
    "current":"Postdoctoral Fellow, Linköping University, Sweden",
    "website":"https://liu.se/en/employee/syeam39",
    "avatar" : "assets/img/scholars/syed_amrr.jpg"
},
#+end_src
** postDocAlumni.json (For alumni.html page)
#+begin_src json
  {
    "name": "Dr. Anirudh Nath",
    "thesis": "",
    "supervisor" : " Prof. Shubhendu Bhasin",
    "year": "2022",
    "current": "",
    "avatar": "assets/img/scholars/anirudh.jpg"
  }
#+end_src
** postdoc.json (For postdoc.html page)
#+begin_src json
{
    "name"    : " Dr. Neha Kailash Nawandar",
    "area"    : " IoT applications, precision agriculture, edge computing",
    "advisor" : " Prof. Shaunak Sen",
    "joining" : " November, 2021",
    "room"    : " Block 2, 339B",
    "email"   : " nnawandar@ee.iitd.ac.in ",
    "avatar"  : "assets/img/scholars/NehaKN.jpg"
}
#+end_src
** projects.json (For projects.html page)
#+begin_src json
{
    "name": "Project Name",
    "pi": "Name of the PI",
    "funding": "Funding Agency"
},
#+end_src
** publications.json (For publications.html page)
** staff.json (For staff.html page)
#+begin_src json
  {
    "name": "Mr. Sunil Kumar",
    "designation": "Junior Technical Superintendent",
    "email": "sunil[at]ee.iitd.ac.in",
    "avatar": "assets/img/staff/staff_sunil.jpg"
  },
#+end_src
** ugcourses.json (For ugcourses.html page)

Same as pgcourses.json
* Project Structure

  |-------------+-------------------------------------------------|
  | File/Folder | Description                                     |
  |-------------+-------------------------------------------------|
  | assets      | Relevant assets for the website                 |
  | assets/data | JSON data for the relevant pages in the website |
  | *.html      | Various pages of the website                    |
  | README.org  | This README file written in Org mode            |
  |-------------+-------------------------------------------------|
* Some key points
- =year= key is important in the alumni json files as this key is used to sort
  the entries at client-side

* Maintainers and Contributors
 - Apurba Das: Data collection, Data entry, Editing
 - Soutrik Bandyopadhyay: Coding in HTML, Vue.js, CSS, Bootstrap Design
 - Neetish Patel: Data entry, Data collation, Editing
 - Dr. Abhilash Patel: Guidance, Technical support
